# Generated by Django 5.1.6 on 2025-02-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionarios', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='groups',
            field=models.ManyToManyField(related_name='funcionarios_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='user_permissions',
            field=models.ManyToManyField(related_name='funcionarios_permissions', to='auth.permission'),
        ),
    ]
