# Generated by Django 5.1.6 on 2025-02-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionarios', '0003_rename_primeiro_nome_funcionario_first_name_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='perfil',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='auth.group'),
        ),
    ]
