# Generated by Django 5.1.6 on 2025-03-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDfuncionarios', '0004_remove_funcionario_perfil_funcionario_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='username',
            field=models.CharField(default='aleatorio', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
